##############################################################################
############################# 发布时该文件不需要修改  ############################

server:
  port: 8080

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://61.145.105.82:8281/zlerp_corporation_zhenglai_dyn?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round&allowMultiQueries=true
#    username: hl_dev
#    password: Zl214365,87

mybatis:
  mapper-locations:
  - "classpath*:com/zlcloud/**/persistence/**/*.xml"

logging:
  level:
    root: info
    ## 如果想要打开mybatis的日志，可将Mapper所在包设置成DEBUG
    com.dky.eureka: debug
    ## 这里设置为info，是因为如果不设置，debug时会不断打印mq日志。
    org.springframework.integration.endpoint.SourcePollingChannelAdapter: info
    com.zlcloud.location.feign.IFeignSysCore: DEBUG

management:
  security:
    enabled: false

